services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true
    bind:
      $nuligaApiToken: '%env(NULIGA_API_TOKEN)%'
      $nuligaClubId: '%env(NULIGA_CLUB_ID)%'

  Mindbird\ContaoNuligaHessen\:
    resource: '../src/'